routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/cron', [PublicController::class, 'cron'])->name('cron');
Route::get('/mobile', [PublicController::class, 'mobile'])->name('mobile');
Route::get('/dates', [PublicController::class, 'dates'])->name('dates');
Route::get('/notifs', [PublicController::class, 'getNotifs'])->name('notifs');
Route::get('/event/{id}', [PublicController::class, 'event'])->name('event');

require __DIR__.'/auth.php';

Auth::routes([
    // 'register' => false
]);

Route::get('/dashboard', [HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => ['auth']], function() {

    // Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('events', EventController::class);
    Route::resource('departments', DepartmentController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'middle_name',
        'birthday',
        'phone',
        'email',
        'password',
        'department_id',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function department(){
        return $this->hasOne(Department::class,'id','department_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Department;
use App\Models\User;
use Auth;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role != 'admin') {
            return redirect('/');
        }

        $users = User::paginate(10);
        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $params['departments'] = Department::all();
        $params['user'] = $user;

        return view('users.edit',$params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $this->validate($request,[
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'middle_name' => 'required|string|max:255',
            'birthday' => 'date|max:255',
            'phone' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'.$user->id,
            'department_id' => 'required|integer'
        ]);

        $user->fill($request->all());
        $user->save();

        return redirect()->route('users.edit',$user->id)
            ->with('success','Details successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Create New Event') }}</span>
                </div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif

                    <form action="{{ route('events.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <strong>Event Name:</strong>
                                    <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="">
                                </div>
                                <div class="form-group">
                                    <strong>Venue:</strong>
                                    <input type="text" name="venue" value="{{ old('venue') }}" class="form-control" placeholder="">
                                </div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>Guests:</strong>
                                            <select name="guests" class="form-control">
                                                <option value="all"{{ old('guests') == 'all' ? ' selected':'' }}>All</option>
                                                <option value="student"{{ old('guests') == 'student' ? ' selected':'' }}>Students only</option>
                                                <option value="faculty"{{ old('guests') == 'faculty' ? ' selected':'' }}>Faculty only</option>
                                                <option value="staff"{{ old('guests') == 'staff' ? ' selected':'' }}>Staff only</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>Department:</strong><br>
                                            @foreach($departments as $department)
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" name="department_ids[]" type="checkbox" id="dep-{{  $department->id }}" value="{{  $department->id }}">
                                                    <label class="form-check-label" for="dep-{{  $department->id }}">{{ $department->name }}</label>
                                                </div><br>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 col-md-6">

                                        <div class="row">
                                            <div class="col-md-6 col-sm-6">
                                                <div class="form-group">
                                                    <strong>Start Date:</strong>
                                                    <input type="date" name="start_date" value="{{ old('start_time') }}" class="form-control" placeholder="MM/DD/YYYY">
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-6">
                                                <div class="form-group">
                                                    <strong>Start Time:</strong>
                                                    <input type="time" name="start_time" value="{{ old('start_time') }}" class="form-control" placeholder="h:m:s a">
                                                </div>  
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-sm-6 col-md-6">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-6">
                                                <div class="form-group">
                                                    <strong>End Date:</strong>
                                                    <input type="date" name="end_date" value="{{ old('end_time') }}" class="form-control" placeholder="MM/DD/YYYY">
                                                </div>
                                            </div>
                                            <div class="col-md-6 col-sm-6">
                                                <div class="form-group">
                                                    <strong>End Time:</strong>
                                                    <input type="time" name="end_time" value="{{ old('end_time') }}" class="form-control" placeholder="h:m:s a">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <strong>Description:</strong>
                                    <textarea rows="5" name="description" class="form-control">{{ old('description') }}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Create Event</button>
                            </div>
                        </div>
                    </form>  

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Edit User') }}</span>
                </div>

                <div class="card-body">
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    <form action="{{ route('users.update',$user->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>First Name:</strong>
                                            <input type="text" name="first_name" value="{{ $user->first_name }}" class="form-control" required>
                                        </div>
                                        <div class="form-group">
                                            <strong>Last Name:</strong>
                                            <input type="text" name="last_name" value="{{ $user->last_name }}" class="form-control" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>Middle Name:</strong>
                                            <input type="text" name="middle_name" value="{{ $user->middle_name }}" class="form-control" required>
                                        </div>
                                        <div class="form-group">
                                            <strong>Birthday:</strong>
                                            <input type="date" name="birthday" value="{{ $user->birthday }}" class="form-control" required>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>Phone:</strong>
                                            <input type="number" name="phone" value="{{ $user->phone }}" class="form-control" placeholder="09" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>Email:</strong>
                                            <input type="text" name="email" value="{{ $user->email }}" class="form-control" required>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    @if(Auth()->user()->role == 'admin')
                                        <div class="col-md-6 col-sm-6">
                                            <div class="form-group">
                                                <strong>Role:</strong>
                                                <select name="role" class="form-control">
                                                    <option value="student"{{ $user->role == 'student' ? ' selected':'' }}>Student</option>
                                                    <option value="faculty"{{ $user->role == 'faculty' ? ' selected':'' }}>Faculty</option>
                                                    <option value="staff"{{ $user->role == 'staff' ? ' selected':'' }}>Staff</option>
                                                    <option value="admin"{{ $user->role == 'admin' ? ' selected':'' }}>Administrator</option>
                                                </select>
                                            </div>
                                        </div>
                                    @endif
                                    <div class="col-md-6 col-sm-6">
                                        <div class="form-group">
                                            <strong>Department:</strong><br>
                                            <select name="department_id" class="form-control">
                                            @foreach($departments as $department)
                                                <option value="{{ $department->id }}" {{ $department->id == $user->department_id ? ' selected':'' }}>{{ $department->name }}</option>
                                            @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <button type="submit" class="btn btn-primary">Update Profile</button>
                            </div>
                        </div>
                    </form>  

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Users') }}</span>
                    {{-- <a href="{{ route('users.create') }}" class="btn btn-primary float-right btn-sm">Create user</a> --}}
                </div>

                <div class="card-body">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif

                    @if( $users->count() )
                    <table class="table table-inverse table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Department</th>
                                <th>Role</th>
                                <th>Option</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td>{{ $user->first_name.' '.$user->last_name }}</td>
                                <td>
                                    @if($user->department)
                                        {{ $user->department->name }}
                                    @endif
                                </td>
                                <td>{{ ucwords($user->role) }}</td>
                                <td>
                                    <a href="{{ route('users.edit',$user->id) }}" class="btn btn-success btn-sm">Edit User</a>
                                    {{-- <form action="{{ route('users.destroy',$user->id) }}" method="POST" style="float:right;">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</a>
                                    </form> --}}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <hr><br>
                    <div id="pager">
                        {{ $users->render(); }}
                    </div>
                    @else
                        <div class="alert alert-info" role="alert">
                            There are no avaialble users to show at the moment.
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('styles')
<style>
#pager div:first-of-type{display: none;}
#pager svg{width: 25px;}
</style>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <span>{{ __('Event Details') }}</span>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                          <tbody>
                            <tr>
                                <td><b>Name:</b></td>
                                <td>{{ $event->name }}</td>
                            </tr>
                            <tr>
                                <td><b>Start Date:</b></td>
                                <td>{{ date('F j, Y, g:i a', strtotime($event->start_date)) }}</td>
                            </tr>
                            <tr>
                                <td><b>End Date:</b></td>
                                <td>{{ date('F j, Y, g:i a', strtotime($event->end_date)) }}</td>
                            </tr>
                            <tr>
                                <td><b>Venue:</b></td>
                                <td>{{ $event->venue }}</td>
                            </tr>
                            <tr>
                                <td><b>Guests</b></td>
                                <td>{{ $event->guests }}</td>
                            </tr>
                            @if($event->departments()->count())
                            <tr>
                                <td><b>Department:</b></td>
                                <td>
                                    @foreach($event->departments() as $dep )
                                    {{$dep->name}} <br>
                                    @endforeach
                                </td>
                            </tr>
                            @endif
                            <tr>
                                <td><b>Desctiption:</b></td>
                                <td>{{ $event->description }}</td>
                            </tr>

                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection